# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/df48fa28-e1a4-48ad-90ca-669a90a8673c";
    fsType = "ext4";
    neededForBoot = true;
  };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/be31b55a-ca09-4531-b880-5886ac8d3793";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-1d503a4405b8.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-4f88fd5967a7.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-4f9ea4f19a90.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-d6386992eaea.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth04615a5.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth2ff2be9.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth41c31fb.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth9814196.useDHCP = lib.mkDefault true;
  # networking.interfaces.vethdd53e9a.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
